---
- name: Configure NTP
  hosts: ntp
  become: true
  roles: [{ role: geerlingguy.ntp, tags: ntp }]

- name: Configure App
  hosts: app
  become: true
  roles: [{ role: geerlingguy.nginx, tags: nginx }]
  tasks:
    - name: Deploy template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
      notify: reload nginx
      tags: app_template

- name: Configure DB
  hosts: db
  become: true
  roles: [{ role: geerlingguy.postgresql, tags: db }]

- hosts: all
  become: true
  handlers:
    - name: reload nginx
      ansible.builtin.service: { name: nginx, state: reloaded }
  post_tasks:
    - name: Debug info
      ansible.builtin.debug:
        msg: "Nginx version check and logs path"
      tags: debug_info
